model_list:
  - model_name: deepseek/deepseek-v4-flash
    litellm_params:
      model: openrouter/deepseek/deepseek-v4-flash
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: "qwen3:latest"
    litellm_params:
      model: "hosted_vllm/qwen3:latest"
      api_base: http://vllm:8000/v1
      api_key: os.environ/VLLM_API_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
